export const productConstants = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_COMPARE_PRODUCT: "ADD_COMPARE_PRODUCT",
    REMOVE_COMPARE_PRODUCT: "ADD_COMPARE_PRODUCT",
};

export const messages = {
    ADD_COMPARE_SUCCESS: "ADD_COMPARE_SUCCESS",
    ALREADY_ADDED_COMPARE: "ALREADY_ADDED_COMPARE",
    REMOVE_COMPARE_SUCCESS: "REMOVE_COMPARE_SUCCESS"
}