// export const productConstants = {
//     PRODUCT_REQUEST: 'PRODUCT_DATA_REQUEST',
//     PRODUCT_SUCCESS: 'PRODUCT_DATA_SUCCESS',
//     PRODUCT_FAILURE: 'PRODUCT_DATA_FAILURE'
// }

export const productConstants = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};