export const PRODUCTS = 
[
    {
        "id_product": 5,
        "brand": "Algenist",
        "category": "Moisturizers",
        "name": "POWER Advanced Wrinkle Fighter Moisturizer",
        "size": "2 oz/ 60 mL",
        "num_reviews": 67,
        "love": 4200,
        "rating": 4.5,
        "price": 85,
        "url": "https://www.sephora.com/product/power-advance",
        "details": "Which skin type is it good for?‚úî Normal‚úî Oily‚úî Combination‚úî Dry‚úî  SensitiveWhat it is:An advanced antiaging moisturizer formulated with the ",
        "how_to_use": "Suggested Usage:-After cleansing- apply to entire face- neck and d√©collete√©. -For optimal results- use after your usual serum.  Precautions:-Use onl",
        "ingredients": "Water- Glycerin- C12-15 Alkyl Benzoate- Caprylic/Capric Triglyceride- Palmitic Acid- Stearic Acid- Chlorella Protothecoides- Algae Exopolysaccharides-"
    },
    {
        "id_product": 15,
        "brand": "Benefit Cosmetics",
        "category": "Eyebrow",
        "name": "Gimme Brow+ Volumizing Eyebrow Gel",
        "size": "0.1 oz/ 3 g",
        "num_reviews": 4000,
        "love": 179100,
        "rating": 4.5,
        "price": 24,
        "url": "https://www.sephora.com/product/gimme-brow-P4",
        "details": "What it is:\r\n\t\r\nA brow-volumizing tinted gel with tiny microfibers that create natural-looking fullness and definition.\r\n\r\nWhat it does:\r\n Benefit‚Äôs",
        "how_to_use": "Suggested Usage:\r\n-Using short pressing motions- stroke the precision tip along the brow to define and shape. \r\n-Brush through with the custom tiny ta",
        "ingredients": "Water- Mica- Glyceryl Stearate- Pentylene Glycol- Polypropylene- Magnesium Aluminum Silicate- PEG-100 Stearate- Phenoxyethanol- Polyacrylamide- C13-14"
    },
    {
        "id_product": 25,
        "brand": "Benefit Cosmetics",
        "category": "Eyebrow",
        "name": "Precisely, My Brow Pencil Ultra Fine Shape & ",
        "size": "0.002 oz/ 0.08 g",
        "num_reviews": 4000,
        "love": 140300,
        "rating": 4.5,
        "price": 24,
        "url": "https://www.sephora.com/product/precisely-my-",
        "details": "What it is: A bestselling brow pencil to transform shapeless- undefined brows with a few strokes‚Äînow available in 12 shades to flatter every hair co",
        "how_to_use": "Suggested Usage:-Hold the pencil along the custom control grip. -To shape brows- use longer- horizontal strokes along the base of your brow. -Fill by ",
        "ingredients": "Stearic Acid- Rhus Succedanea Fruit Wax- Talc- Hydrogenated Castor Oil- Paraffinum Liquidum (Mineral Oil)- Cera Microcristallina (Microcrystalline Wax"
    },
    {
        "id_product": 35,
        "brand": "Benefit Cosmetics",
        "category": "Mascara",
        "name": "They‚Äôre Real! Lengthening & Volumizing Masc",
        "size": "0.3 oz/ 8.5 g",
        "num_reviews": 15000,
        "love": 287300,
        "rating": 4,
        "price": 25,
        "url": "https://www.sephora.com/product/they-re-real-",
        "details": "What it is:A lengthening mascara that curls- volumizes- lifts- and separates lashes for an \"out-of-here\" look.What it does:This breakthrough bestselle",
        "how_to_use": "Suggested Usage:\r\n-Position wand horizontally and wiggle from side to side and base to tip to achieve maximum volume and length and lift.\r\n-Hold wand ",
        "ingredients": "Water- Paraffin- Polybutene- Styrene/Acrylates/Ammonium Methacrylate Copolymer- Beeswax (Cera Alba)- Bisdiglyceryl Polyacyladipate2- C1836 Acid Trigly"
    },
    {
        "id_product": 45,
        "brand": "Christian Louboutin",
        "category": "Lipstick",
        "name": "Velvet Matte Lip Colour",
        "size": "0.134 oz",
        "num_reviews": 94,
        "love": 40800,
        "rating": 4.5,
        "price": 90,
        "url": "https://www.sephora.com/product/velvet-matte-",
        "details": "What it is:\r\n A highly-pigmented matte lip color that provides non-drying comfort on the lips and leaves a suede finish.\r\n\r\nWhat it does:\r\nThis Intens",
        "how_to_use": "Suggested Usage:\r\n-Apply the rich Velvet Matte formula directly from the tube. \r\n-For enhanced results- use with Christian Louboutin's Lip Definer.\r\n-",
        "ingredients": "Dimethicone- Pentaerythrityl Tetraisostearate- Synthetic Wax- Octyldodecanol- Methyl Methacrylate Crosspolymer- Polyethylene- Kaolin- Polyglyceryl-2 T"
    },
    {
        "id_product": 55,
        "brand": "tarte",
        "category": "Lipstick",
        "name": "SEA Color Splash Lipstick",
        "size": "0.12 oz/ 3.6 mL",
        "num_reviews": 1000,
        "love": 168100,
        "rating": 4.5,
        "price": 21,
        "url": "https://www.sephora.com/product/sea-color-spl",
        "details": "What it is: A long-wearing- pigment-rich lipstick that‚Äôs offered in an array of creamy shades.What it does:Color Splash Lipstick offers intense pigm",
        "how_to_use": "Suggested Usage:-Use the tapered tip to define and contour lips.¬†-For the perfect shape- start in the middle of lips and smooth out toward the corner",
        "ingredients": "Copolymer- Palmitoyl Tripeptide-1- Tribehenin- Sorbitan Isostearate- Sorbitan Oleate- Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate- Calcium "
    },
    {
        "id_product": 65,
        "brand": "TOM FORD",
        "category": "Lipstick",
        "name": "Lip Color Lipstick",
        "size": "0.1 oz/ 2.96 mL",
        "num_reviews": 327,
        "love": 119100,
        "rating": 4.5,
        "price": 55,
        "url": "https://www.sephora.com/product/lip-color-P41",
        "details": "What it is: A luxurious lipstick in an array¬†of essential shades for the many dimensions of the TOM FORD woman.Highlighted Ingredients: - Soja Seed E",
        "how_to_use": "Suggested Usage:-May be applied directly to the lips from the bullet or with a lip brush.-Layer with any other texture or tone to create a custom colo",
        "ingredients": "Ricinus Communis (Castor) Seed Oil- Diisostearyl Malate- Trioctyldodecyl Citrate- Caprylic/Capric Triglyceride- Lanolin Oil- Euphorbia Cerifera (Cande"
    },
    {
        "id_product": 75,
        "brand": "TOM FORD",
        "category": "Lipstick",
        "name": "Lip Blush",
        "size": null,
        "num_reviews": 21,
        "love": 4500,
        "rating": 3.5,
        "price": 55,
        "url": "https://www.sephora.com/product/lip-blush-P44",
        "details": "What it is: A gold-flecked moisturizing lipstick balm that applies on clear and instantly transforms into a sultry pink stain. Ingredient Callouts: Fr",
        "how_to_use": "Suggested Usage:-Apply directly onto lips as desired.",
        "ingredients": "Hydrogenated Polyisobutene- Octyldodecanol- Pentaerythrityl Tetraisostearate- Neopentyl Glycol Dicaprate- Polyglyceryl-2 Triisostearate- Dibutyl Lauro"
    },
    {
        "id_product": 85,
        "brand": "Too Faced",
        "category": "Lipstick",
        "name": "Natural Nudes Lipstick",
        "size": "0.12 oz/ 3.6 g",
        "num_reviews": 241,
        "love": 64500,
        "rating": 4.5,
        "price": 22,
        "url": "https://www.sephora.com/product/natural-nudes",
        "details": "What it is: A richly-pigmented- creamy- natural nude lipstick.What it does: Bare it all with this richly-pigmented collection of creamy- natural nude ",
        "how_to_use": "Suggested Usage:- Exfoliate lips prior to applying color for the smoothest application.- Prep lips with Lip Insurance (sold separately) to lock down c",
        "ingredients": "Polybutene- Bis-Diglyceryl Polyacyladipate-2- Octyldodecanol- Polyethylene- Isononyl Isononanoate- Ethylhexyl Palmitate- Hydrogenated Styrene/Methyl S"
    },
    {
        "id_product": 95,
        "brand": "TOM FORD",
        "category": "Moisturizers",
        "name": "Intensive Purifying Mud Mask",
        "size": "3.4 oz/ 100 mL",
        "num_reviews": 1,
        "love": 413,
        "rating": 5,
        "price": 67,
        "url": "https://www.sephora.com/product/intensive-pur",
        "details": "Which skin type is it good for?\r\n‚úî Normal\r\n‚úî Oily\r\n‚úî Combination\r\n‚úî Dry\r\n‚úî  Sensitive\r\n\r\nWhat it is:A velvety mud mask that draws out impuri",
        "how_to_use": null,
        "ingredients": "Water- Kaolin- Bentonite- Butylene Glycol- Glycerin- Charcoal Powder- Aloe Barbadensis Leaf Juice- Hypnea Musciformis (Algae) Extract- Gellidiela Acer"
    },
    {
        "id_product": 105,
        "brand": "Volition Beauty",
        "category": "Moisturizers",
        "name": "Celery Green Cream with Hyaluronic Acid + Pep",
        "size": "1.7 oz/ 50mL",
        "num_reviews": 359,
        "love": 11500,
        "rating": 4.5,
        "price": 55,
        "url": "https://www.sephora.com/product/celery-green-",
        "details": "What it is: An oil-free- celery-powered moisturizer that purifies and helps improve hydration retention for poreless- healthier-looking skin.Skin Type",
        "how_to_use": "Suggested Usage:-Twice daily- apply to face- neck- and d√©colletage. Precautions:-For external purposes only.-Avoid direct contact with eyes.",
        "ingredients": " -Celery Seed Extract: Helps smooth- blur- and minimize the appearance of pores.-Hyaluronic Acid: Replenishes and retains moisture.-Peptides: Hydrates"
    },
    {
        "id_product": 115,
        "brand": "Youth To The People",
        "category": "Moisturizers",
        "name": "Adaptogen Deep Moisture Cream with Ashwagandh",
        "size": "2 oz/ 60 mL",
        "num_reviews": 1000,
        "love": 46200,
        "rating": 4.5,
        "price": 58,
        "url": "https://www.sephora.com/product/adaptogen-dee",
        "details": "What it is:  A hydrating moisturizer with superior plant extracts and a pro-grade peptide complex formulated for dry- reactive- and sensitive skin.Ski",
        "how_to_use": "Suggested Usage:-Morning and night- apply to the  skin until fully absorbed. ",
        "ingredients": " -Squalane: Mimics your skin‚Äôs natural oils to boost skin hydration while minimizing the risk of clogged pores.-Ashwagandha: Helps reduce visible si"
    },
    {
        "id_product": 125,
        "brand": "Tatcha",
        "category": "Moisturizers",
        "name": "The Dewy Skin Cream",
        "size": null,
        "num_reviews": 1000,
        "love": 99900,
        "rating": 4,
        "price": 68,
        "url": "https://www.sephora.com/product/the-dewy-skin",
        "details": "What it is: A rich cream that feeds skin with plumping hydration and antioxidant-packed Japanese purple rice for a dewy- healthy glow. \r\nSkin Type: No",
        "how_to_use": "Suggested Usage:-Scoop a pearl-sized amount of cream with the gold spoon. -Massage onto face- neck- and d√©colletage in upward strokes. -Use daily- mo",
        "ingredients": "Aqua/Water/Eau- Saccharomyces/Camellia Sinensis Leaf/Cladosiphon Okamuranus/Rice Ferment Filtrate*- Glycerin- Propanediol- Dimethicone- Squalane- Diis"
    },
    {
        "id_product": 126,
        "brand": "Horrible Brand",
        "category": "Lipstick",
        "name": "Terrible Lipstick",
        "size": "7 Gallons",
        "num_reviews": 38,
        "love": 420,
        "rating": 5,
        "price": 3,
        "url": "https://www.youtube.com/",
        "details": "The last lipstick you will ever need",
        "how_to_use": "Put on lips",
        "ingredients": "Lipstick Stuff"
    }
]

export const PRODUCT = {
    "id_product": 5,
    "brand": "Algenist",
    "category": "Moisturizers",
    "name": "POWER Advanced Wrinkle Fighter Moisturizer",
    "size": "2 oz/ 60 mL",
    "num_reviews": 67,
    "love": 4200,
    "rating": 4.5,
    "price": 85,
    "url": "https://www.sephora.com/product/power-advance",
    "details": "Which skin type is it good for?‚úî Normal‚úî Oily‚úî Combination‚úî Dry‚úî  SensitiveWhat it is:An advanced antiaging moisturizer formulated with the ",
    "how_to_use": "Suggested Usage:-After cleansing- apply to entire face- neck and d√©collete√©. -For optimal results- use after your usual serum.  Precautions:-Use onl",
    "ingredients": "Water- Glycerin- C12-15 Alkyl Benzoate- Caprylic/Capric Triglyceride- Palmitic Acid- Stearic Acid- Chlorella Protothecoides- Algae Exopolysaccharides-"
}